#!/bin/sh -e
#
# 2017 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "$__global/explorer/os")
state=$(cat "$__object/parameter/state")
source="$(cat "$__object/parameter/source")"
if [ "$source" = "-" ]; then
   source="$__object/stdin"
fi


if [ -f "$__object/parameter/destination" ]; then
   destination="$(cat "$__object/parameter/destination")"
else
   unit="$__object_id"
   destination="/etc/systemd/system/$unit"
fi

case "$os" in
   centos|ubuntu)
      __package systemd
      # whitelist safeguard
      __file "$destination" \
         --owner root --group root --mode 0644 \
         --state "$state" \
         --source "$source"
   ;;
   *)
      echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
      echo "Please contribute an implementation for it if you can." >&2
      exit 1
   ;;
esac
